services:
  postgres:
    image: postgres:18
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend

  app:
    image: xiapuna/locmns-back:0.0.2
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - backend

#  front:
#    image: xiapuna/locmns-front
#    ports:
#      - "80:80"

volumes:
  postgres_data:

networks:
  backend: